# Section 1 {.unnumbered}

Last Updated: 14 Sept 2023

Date: 15 Sept 2023


## Introduction
In this section, we will discuss:

- $\sigma$-algebras
- Borel $\sigma$-algebras
- Probability measures
- Random variables and random vectors
- Limits of events
- Independence 
- Uniqueness and $\pi-\lambda$


## $\sigma$-algebras

In the STAT 210 textbook, we defined a $\sigma$-algebra as follows:

*Definition 2.2.1 from textbook*

::: {#def-sigma-algebra}

A $\sigma$-algebra on $\Omega$ is a collection $\mathcal{F}$ of subsets of $\Omega$ such that:

1. $\emptyset \in \mathcal{F}$.

2. If $A \in \mathcal{F}$, then $A^c \in \mathcal{F}$.

3. If $A_1, A_2, \cdots \in \mathcal{F}$, then $\cup_{j=1}^{\infty} A_j \in \mathcal{F}$.
:::


### ✏️ Pencil 2.2.5
Show that $\sigma$-algebra is automatically closed under countable intersections, i.e. if $A_1, A_2, \cdots$ are in the $\sigma$-algebra $\mathcal{F}$, then $\cap_{j=1}^{\infty} A_j \in \mathcal{F}$. Then, show that the requirement $\emptyset \in \mathcal{F}$ can be replaced by the requirements $\mathcal{F} \neq \emptyset$.

::: {.callout-tip collapse="true" appearance="simple"}

## Solution 
Will be added after section. 😛
<!--
If $A_1, A_2, \cdots \in \mathcal{F}$, by De Morgan's laws, $\bigcap_{j=1}^{\infty} A_j = \left(\bigcup_{j=1}^{\infty} A_j^c \right)^c \in F$ since each $A_j^c \in \mathcal{F}$, which implies that $\bigcup_{j=1}^{\infty} A_j^c \in \mathcal{F}$, which further implies that $\left(\bigcup_{j=1}^{\infty} A_j^c \right)^c \in F$. 

Also note that if $\mathcal{F} \notin \emptyset, \mathcal{F}$ contains some element of A. Then $A \cap A^c = \emptyset \in \mathcal{F}$.
-->
:::

::: {.callout-note}
## Tip: De Morgan Laws

$$\left(\bigcup_{n=1}^{\infty} A_n \right)^c = \bigcap_{n=1}^{\infty} A_n ^c.$$

$$\left(\bigcap_{n=1}^{\infty} A_n \right)^c = \bigcup_{n=1}^{\infty} A_n ^c.$$
:::


### ✏️ Pencil 2.2.6

Check that an intersection of $\sigma-$algebras, even uncountably many, is $\sigma$-algebra. Give a simple example showing that a union of $\sigma$-algebras may not be a $\sigma$-algebra.

::: {.callout-tip collapse="true" appearance="simple"}

## Solution
Will be added after section. 😛
<!--
Let $\{\mathcal{F}_i\}_{i\in I}$ be $\sigma$-algebras, and consider $\mathcal{F}' = \cup_{i\in I} \mathcal{F}_i$. Since each $\mathcal{F}_i contains \emptyset$, $\emptyset \in \mathcal{F}'$. If $A\in \mathcal{F}'$, $A\in \mathcal{F}_i \forall i\in I$, which implies that $A^c \in \mathcal{F}_i \forall i \in I$, so is $A^c \in \mathcal{F}'$. If $A_1, A_2, \cdots, \in \mathcal{F}'$, $\bigcup_{j=1}^{\infty} A_j \in \mathcal{F}_i \forall i\in I$, which implies that $\bigcup_{j=1}^{\infty} A_j \in \mathcal{F}'$.

Let $\mathcal{F_1} = \{\emptyset, \{a\},  \{b,c\},  \{a, b, c\}\}$ and $\mathcal{F_2} = \{\emptyset, \{a,b\},  \{c\},  \{a, b, c\}\}$, note that $\mathcal{F_1} \cup \mathcal{F_2}$ contains $\{a,b\}$ and $\{b,c\}$, but not their intersection.
-->
:::


:::{.callout-important  appearance="simple"}
As noted in the textbook as well as Hazard 2.2.2, a $\sigma$-algebra $\mathcal{F}$ is a collection of sets, and an element of $\mathcal{F}$ is a subset of $\omega$. An intersection of $\sigma$-algebras is very different from an intersection of events!
:::


## Borel $\sigma$-algebras

*Definition 2.3.1 from textbook*

::: {#def-borel-sigma-algebra}
 The Borel $\sigma$-algebra $\mathcal{B}$ on $\mathbb{R}$ is defined to be the $\sigma$-algebra generated by all open intervals $(a,b)$ with $a,b\in \mathbb{R}$. A *Borel set* is a set in the Borel $\sigma$-algebra.
:::



### ✏️ Pencil 2.3.2

Show that the Borel $\sigma$-algebra is the same if we use closed intervals $[a,b]$ instead of open intervals to generate it, and that it is also the same if we use "semi-inifinite"  intervals $(-\infty,b)$ to generate it.

::: {.callout-tip collapse="true" appearance="simple"}

## Solution 
Will be added after section. 😛
<!--
$[a,b] = ((-\infty, a) \cup (b,\infty))^c\in \mathcal{B}. (-\infty, b]=(b, \infty)^c \in \mathcal{B}$. Furhtermore, since $\mathbb{Q}$ is dense in $\mathbb{R}$, there always exists a sequence of rationals that converge to any real number, so $(-\infty, b]$ for $b\in \mathbb{R}$ can be obtained from the union $(-\infty, b_n) \forall b_n \in \mathbb{Q}$, and letting $n \rightarrow \infty$.
-->
:::


## Probability Measure

*Section 2.5 from textbook*

::: {#def-probability}
A *probability space* $(\Omega, \mathcal{F}, P)$ consists of a measurable space $(\Omega, \mathcal{F})$ and a map (the probability function) $P$ satisfying the following axioms:

1.  $P(\emptyset) = 0$, $P(\Omega) = 1$.
2.  $\forall A \in \mathcal{F}$, $P(A) \geq 0$.
3.  If $\{A_i\}^{\infty}_{i=1}$ is a collection of mutually disjoint sets in $\mathcal{F}$, i.e. $\forall i \neq j$, $A_i \cap A_j = \emptyset$, then 
    $$P\left( \bigcup_{i=1}^{\infty} A_i \right) = \sum_{i=1}^{\infty} P(A_i). $$
\end{itemize}
This property is known as $\sigma$-additivity.
:::

### ✏️ Pencil 2.5.1

Show that in the first axiom, the condition $P(\emptyset) = 0$ can be eliminated.

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛
<!--
By the first axiom, $P(\sigma)=1$, and by the second axiom, we find that $P(\sigma)=P(\sigma \cup \emptyset) = P(\sigma)+ P(\emptyset)$ since each $\sigma$ and $\emptyset$ are disjoint by definition, $P(\emptyset)=0$ follows.
-->
:::

### ✏️ Section Problem 1

Show that $P$ is subadditive, i.e. if $\{A_i\}^{\infty}_{i=1}$ is \textit{any} collection of sets in $\mathcal{F}$, then
    $$P\left( \bigcup_{i=1}^{\infty} A_i\right) \leq  \sum_{i=1}^{\infty} P(A_i).$$

::: {.callout-tip collapse="true" appearance="simple"}

## Solution
Will be added after section. 😛
<!--
Let us construct a new collection of subsets of $\Omega$, denoted by $\{B_i\}_{i=1}^{\infty}$, where
    $$B_1 = A_1 \text{  and  } B_i = A_i \cap \Big (\bigcup_{j=1}^{i-1}A_j  \Big )^c, i \geq 2 $$
    
We observe that, $B_i \in \mathcal{F}$, $\forall i\geq 1$. Moreover, $B_i$'s are disjoint and satisfies $\bigcup_{i=1}^{\infty} A_i = \bigcup_{i=1}^{\infty} B_i$. This technique of constructing disjoint sets that preserve unions from a general list of sets is called disjointification. We further note that $B_i \subseteq A_i$, $\forall i\geq 1$, implying $P(B_i) \leq P(A_i)$, $\forall i\geq 1$. Using the $\sigma$-additivity of probability we get
$$P \left(\bigcup_{i=1}^{\infty} A_i\right) = P\left(\bigcup_{i=1}^{\infty} B_i\right) = \sum_{i=1}^{\infty}P(B_i) \leq \sum_{i=1}^{\infty}P(A_i).$$
-->
:::


### ✏️ Section Problem 2

Let $A_1,A_2,...$ be a sequence of sets in $\mathcal{F}$ such that $A_n\uparrow A$ as $n\to \infty$. Show that, $P(A_n) \xrightarrow{n \to \infty} P(A)$. Show that the result also holds for $A_n \downarrow A$. Does the result hold for any measure?


::: {.callout-tip collapse="true" appearance="simple"}

## Solution
Will be added after section. 😛

<!--
 The notation $A_n \uparrow A$ means that we have a list of increasing sets $A_1 \subseteq A_2 \subseteq ... $ with the limit being equal to their union, i.e. $A = \bigcup_{i=1}^{\infty}A_i$ $ (\in \mathcal{F})$. Let us construct $\{B_i\}_{i=1}^{\infty}$ by disjointifying $\{A_i\}_{i=1}^{\infty}$, as part (i). We observe that,
    $$P(A_n) = P(\bigcup_{i=1}^{n} A_i) = P(\bigcup_{i=1}^{n} B_i) = \sum_{i=1}^{n}P(B_i) \xrightarrow{n\to \infty} \sum_{i=1}^{\infty} P(B_i) = P(\bigcup_{i=1}^{\infty} B_i) = P(A)$$
    This property is also known as `continuity from below'.
    
    
Analogously, $A_n \downarrow A$ means we have a list of decreasing sets $A_1 \supseteq A_2 \supseteq ... $ with the limit being equal to their intersection, i.e. $A = \bigcap_{i=1}^{\infty}A_i$ $(\in \mathcal{F})$. For this case, let $C_i = A_1 \backslash A_i$, $i \geq 1$. Then $C_n \uparrow A_1 \backslash \bigcap_{i=1}^{\infty}A_i = A_1 \backslash A$. Applying the previous result, we get
    $$P(C_n) \xrightarrow{n\to \infty} P(A_1\backslash A) = P(A_1) - P(A) $$
     We complete the proof by noting that $P(C_n) = P(A_1) - P(A_n)$. This property is also known as `continuity from above'.
     Let $m$ be a general measure. Following similar steps as above, one can prove that $m$ is continuous from below. However, $m$ is not continuous from above, in general. As a counterexample, suppose $\Omega = \mathbb{R}, \mathcal{F}=\mathcal{B}$ (the Borel $\sigma$-algebra on $\mathbb{R}$) and $m$ is the Lebesgue measure on $\mathbb{R}$. Let $A_n = [n,\infty)$, $n\geq 1$. Here $m(A_n) = \infty$, $\forall n\geq 1$, but $A_n \downarrow \emptyset$ and $m(\emptyset) = 0$. Notice that, the continuity property holds for a sequence of sets $A_n \downarrow A$ and a general measure $m$ if $m(A_k)$ is finite for some $k \geq 1$.  
-->
:::


## Random Variables and Random Vectors
*Definition 2.6.1 from textbook*

::: {#def-random-variable}
A *random variable* is a measurable function $X$ from $\sigma$ to $\mathbb{R}$, where "measurable" means that the preimage $X^{-1}(\mathcal{B}) = \{\omega \in \sigma : X(\omega) \in \mathcal{B}\}$ is in $\mathcal{F}$ for all Borel sets $\mathcal{B}$.
:::

::: {#def-random-vector}
A *random vector* in $\mathbb{R}^n$ is a measurable function $\mathbf{X}$ from $\sigma$ into $\mathbb{R}^n$, where "measurable" means that the preimage $\mathbf{X}^{-1} (\mathcal{B}) \equiv \{\omega \in \sigma: \mathbf{X}(\omega) \in \mathcal{B}\}$ is in $\mathcal{F}$ for all Borel sets $\mathcal{B}$ in $\mathbb{R}^n$.
:::

### ✏️ Pencil 2.6.2

Show that if $X$ is a random variable, then so is $g(X)$ for any measurable function $g$.

::: {.callout-tip collapse="true" appearance="simple"}

## Solution
Will be added after section. 😛
<!--
$X$ is a random variable. By definiton, $X^{-1}(\mathcal{B}) \in \mathcal{F}$. $g$ is measurable, so $g^{-1}(\mathcal{B})$ is Borel. Thus, $(gX)^{-1}(\mathcal{B}) = X^{-1}(g^{-1}(\mathcal{B})) \in \mathcal{F}$, so $g(X)$ is a random variable.
-->
:::

### ✏️ Pencil 2.7.2

Let $F(x,y)$ be a bivariate CDF. Prove that for all $a_1 \leq b_1$ and $a_2 \leq b_2$, 
$$F(b_1, b_2)-F(a_1, b_2)-F(b_1,a_2)+F(a_1,a_2) \geq 0.$$

::: {.callout-tip collapse="true" appearance="simple"}

## Solution
Will be added after section. 😛
<!--
By the axiom of probability, observe that:
$$
\begin{align*}
F(&b_1, b_2)-F(a_1, b_2)-F(b_1,a_2)+F(a_1,a_2)  \\
&= P(X \leq b_1, Y \leq b_2) - P(X \leq a_1, Y\leq b_2)\\
&-P(X \leq b_1, Y \leq a_2) + P(X \leq a_1, Y\leq a_2)\\
&= P(a \leq X \leq b_1, Y \leq b_2) - P(a_1 \leq X\leq b_1, Y \leq a_2)\\
&= P(a_1 \leq X \leq b_1, a_2 \leq Y \leq b_2)\\
&\geq 0\\
\end{align*}
$$
-->
:::


## Limits of Events
*Section 2.8 from textbook*

::: {#def-lim}
Let $A_1, A_2,...$ be a sequence of events on $(\Omega, \mathcal{F}, P)$. Define

$$B_n = \bigcup_{m=n}^{\infty} A_m ,\hspace{0.2cm} C_n = \bigcap_{m=n}^{\infty} A_m, \hspace{0.2cm} n\geq 1 .$$

Then, $C_n \subseteq A_n \subseteq B_n$, $\forall n\geq 1 $, and $\{B_n\}^{\infty}_{n=1}$ and $\{C_n\}^{\infty}_{n=1}$ are decreasing and increasing respectively. Let $B$ and $C$ be their respective limiting sets. Then,

$$B = \bigcap_{n=1}^{\infty}\bigcup_{m=n}^{\infty} A_m ,\hspace{0.2cm} C = \bigcup_{n=1}^{\infty} \bigcap_{m=n}^{\infty} A_m  $$
We call $B$ and $C$, $\limsup\limits_{n \to \infty}A_n$ and $\liminf \limits_{n \to \infty}A_n$, respectively.
:::


### ✏️ Section Problem 3
Show that $B = \{\omega \in \Omega : \omega \in A_n \text{ for infinitely many values of } n\}$.

::: {.callout-tip collapse="true" appearance="simple"}

## Solution
Will be added after section. 😛
<!--
It is useful to think about "$\bigcup$" as "there exists" ($\exists$) and "$\bigcap$" as "for all" ($\forall$). So,
$$
\begin{eqnarray*}
    \omega \in B &\iff& \omega \in \bigcap_{n=1}^{\infty} B_n\\
    & \iff & \omega \in B_n, \hspace{0.2cm}\forall n\geq 1\\
    & \iff & \forall n\geq 1, \hspace{0.2cm} \omega \in \bigcup_{m=n}^{\infty} A_m\\
    & \iff & \forall n\geq 1, \hspace{0.1cm} \exists m_n\geq n \text{ such that } \omega \in A_{m_n}\\
    & \iff & \omega \in A_n \text{ for infinitely many values of } n
    \end{eqnarray*}
$$
-->
:::


### ✏️ Section Problem 4
Show that $C = \{\omega \in \Omega: \omega \in A_n \text{ for all but finitely many values of } n\}$.

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛

<!--
We observe that,
$$
    \begin{eqnarray*}
    \omega \in C &\iff& \omega \in \bigcup_{n=1}^{\infty} C_n\\
    & \iff & \exists n\geq 1 \text{ such that } \omega \in C_n \\
    & \iff & \exists n\geq 1 \text{ such that } \omega \in \bigcap_{m=n}^{\infty} A_m\\
    & \iff & \exists n\geq 1 \text{ such that } \forall m\geq n,  \omega \in A_m\\
    & \iff & \omega \in A_n \text{ for all but finitely many values of } n
    \end{eqnarray*}
$$
    We can also prove this result by using part (i). Notice that  $$ \begin{align*}C^c &= \Big(\bigcup_{n=1}^{\infty} \bigcap_{m=n}^{\infty} A_m \Big)^c \\ &= \bigcap_{n=1}^{\infty} \bigcup_{m=n}^{\infty} A^c_m \\ &= \{\omega \in \Omega : \omega \in A^c_n \text{ for infinitely many values of } n\} \end{align*}$$. 
    
Thus, $$ \begin{align*} C &= \{\omega \in \Omega: \omega \in A^c_n \text{ for finitely many values of } n\}  \\ &= \{\omega \in \Omega: \omega \in A_n \text{ for all but finitely many values of } n\} \end{align*}$$
-->
:::

::: {#def-limits-to-An}
We say that the sequence of events $\{A_n\}^{\infty}_{n=1}$  "has a limit $A$", if $B = C$ and the common set is equal to $A$. In that case, we write $\lim\limits_{n\to \infty} A_n = A$.
:::

### ✏️ Section Problem 5
Assume the above is the case. Show that $A \in \mathcal{F}.$

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛
:::


### ✏️ Section Problem 6
Show that $\lim\limits_{n \to \infty} P(A_n) = P(A)$.

::: {.callout-note}
## Tip: A useful inequality

$$P(\liminf\limits_{n \to \infty}A_n) \leq \liminf\limits_{n \to \infty}P(A_n) \leq \limsup\limits_{n \to \infty}P(A_n) \leq P(\limsup\limits_{n \to \infty}A_n).$$
:::

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛
<!--
Note that, the result is immediate if we can prove (1). We shall now show that (1) holds for a general sequence of events $\{A_n\}_{n=1}^{\infty}$.\\
    We know that (from Problem 2)
    $$P(\liminf\limits_{n\to \infty} A_n) =  \lim \limits_{n\to \infty} P(C_n)$$
    Note that $C_n \subseteq A_n$, $\forall n \geq 1$, which implies $P(C_n) \leq P(A_n)$. Hence we have,
    $$\lim \limits_{n\to \infty} P(C_n) = \liminf \limits_{n\to \infty} P(C_n) \leq \liminf\limits_{n\to \infty} P(A_n) $$
    Similarly, we have
    $$P(\limsup\limits_{n\to \infty} A_n) =  \lim \limits_{n\to \infty} P(B_n) $$
    Note that $B_n \supseteq A_n$, $\forall n \geq 1$, which implies $P(B_n) \geq P(A_n)$. Hence we have,
    $$\lim \limits_{n\to \infty} P(B_n)=\limsup \limits_{n\to \infty} P(B_n) \geq \limsup\limits_{n\to \infty} P(A_n) $$
Finally, it is always true that
    $$\liminf\limits_{n\to \infty} P(A_n) \leq \limsup\limits_{n\to \infty} P(A_n)$$
-->
:::


## Independence
::: {#def-indepence-RV}
Two random variables $X_1,X_2$ are *independent* if the event $X_1\in B_1$ is independent of the event $X_2\in B_2$ for all Borel $B_1, B_2$
:::

As remarked in Remark 2.9.12, it is helpful and simple to think directly about distributions and preimages. In set operations, if $f$ is a function from a set $S$ into a set $T$, and $B_{\alpha} \subseteq T$ for all $\alpha$ in some index set $A$, we then have the following convenient properties:

1. $f^{-1}(\cup_\alpha B_{\alpha}) = \cup_\alpha f^{-1} (B_\alpha)

2. $f^{-1}(\cap_\alpha B_{\alpha}) = \cap_\alpha f^{-1} (B_\alpha)

3. $f^{-1} (B_\alpha^C) =(f^{-1}(B_\alpha))^C

### ✏️ Pnecil 2.9.13 

Verify the above properties of preimages

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛
<!--
1. Suppose $x\in f^{-1}(\cup_\alpha B_{\alpha})$, then note that $f(x) \in \cup_\alpha B_\alpha$, which implies that $f(x) \in B_\alpha$ for some $\alpha$. Thus, $x \in f^{-1} (B_\alpha) for some $\alpha$, which implies $x \in \cup_\alpha f^{-1} (B_\alpha)$.

2. Suppose $x\in f^{-1}(\cap_\alpha B_{\alpha})$. Analogously, by replacing "some" with "all", $x\in \cap_\alpha f^{-1} (B_\alpha)$

3. Suppose $x\in f^{-1} (B_\alpha^C)$, then $f(x) \in B_\alpha^C$, which is equivalent to $f(x)\notin B_\alpha$. Thus, $x\notin f^{-1}(B_\alpha)$, which implies that $x\in (f^{-1}(B_\alpha))^C$
-->
:::


### ✏️ Pnecil 2.9.15 

If $\mathbf{X}_1, \mathbf{X}_2 , \mathbf{X}_3$ are random vectors (possibly in different dimensions) with $\mathbf{X}_1  \perp\!\!\!\perp \mathbf{X}_2$ and $(\mathbf{X}_1 , \mathbf{X}_2) \perp\!\!\!\perp \mathbf{X}_3$, then $\mathbf{X}_1, \mathbf{X}_2 , \mathbf{X}_3$ are independent.

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛
<!--
$$
\begin{align*}
P(\mathbf{X}_1 \in A, \mathbf{X}_2 \in B, \mathbf{X}_3 \in C) 
&= P(\mathbf{X}_1, \mathbf{X}_2 \in A \times B, \mathbf{X}_3 \in C)\\
&= P(\mathbf{X}_1, \mathbf{X}_2 \in A \times B)P(\mathbf{X}_3 \in C)\\
&= P(\mathbf{X}_1 \in A, \mathbf{X}_2 \in B)P(\mathbf{X}_3 \in C)\\
&= P(\mathbf{X}_1 \in A)P(\mathbf{X}_2 \in B)P(\mathbf{X}_3 \in C)\\
\end{align*}
$$
-->
:::

## Uniqueness and $\pi-\lambda$

::: {#def-indepence-RV}
A collection $\mathcal{A}$ of subsets of $\Omega$ is called a *$\pi-$system* if $A\cap B\in \mathcal{A}$ for all $A, B\in \mathcal{A}$ The collection $\mathcal{L}$ of subsets of $\Omega$ is called a *$\lambda-system$* if the following conditions hold:

1. $\Omega \in \mathcal{L}$

2. (Closure under proper difference) If $A, B \in \mathcal{L}$ with $A \subseteq B$, then $B \ A \in \mathcal{L}

3. (Closure under increasing unions) If $A_1 \subseteq A_2 \subseteq \cdots$ are in $\mathcal{L}$, then $\bigcup_{i=1}^\infty A_i \in \mathcal{L}$
:::


### ✏️ Pnecil 2.10.2 

Show that if $\mathcal{A}$ is both a $\pi$-system and a $\lambda$-system, then it is a $\sigma$-algebra.

::: {.callout-tip collapse="true" appearance="simple"}
## Solution
Will be added after section. 😛
<!--
$\Omega \in \mathcal{A}$, so for any $A\in \mathcal{A}$, $A \subseteq \Omega$. This implies that $\Omega-A = A^c \in \mathcal{A}$. Trivially, we also observe that $\mathcal{A}\neq \emptyset$. Finally, if $A_1, A_2, \cdots \in \mathcal{A}$, then $A_1 \cap A_2 \cap \cdots \subseteq \cdots \subseteq A \in \mathcal{A}$, so their union $\bigcup_{i=1}^\infty A_i \in \mathcal{A}$
-->
:::

## Next Week
Next week, we will discuss:

- Discuss more $\pi-\lambda$
- Reasoning by representation

Feel free to upload the pencil problem you wish to be discussed next week [here](https://forms.gle/RBmMNYJp4u3qD5W79).

Note that a verified email address is needed in the GForm so we don't get scammy input! :) 

$\,$
