project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  
book:
  title: "STAT 210 Section Notes"
  author: "Zad Chin & Jarell Cheong"
  favicon: assets/img/stat210-clear_bg.png
  output-file: "users-guide"
  reader-mode: true
  public-url: https://zadchin.github.io/STAT210_Section/
  repo-url: https://github.com/zadchin/STAT210_Section
  repo-actions: [issue]
  chapters:
    - index.qmd
    - 01_Section_1.qmd
    - 02_Section_2.qmd
    - 03_Section_3.qmd
    - 04_Section_4.qmd
    - 05_Section_5.qmd
    - 06_Section_6.qmd
    - 07_Section_7.qmd
    - meme.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: style.css
    include-before-body:
      - _dollars.tex
      - _bold_html.tex
      - _macros.tex
      - _dollars.tex
        
  pdf:
    documentclass: scrreprt
    include-in-header:
      - _bold.tex
      - _macros_pdf.tex
